version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
environment:
  isappveyor: 1
services: mssql2016
nuget:
  project_feed: true
before_build:
- cmd: nuget restore C:\projects\vega\Vega.sln
build:
  project: Vega.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
test: on
deploy:
- provider: NuGet
  api_key:
    secure: oy2gsamo6qfdzw44hf3a6brkkoere6rujpizzd6txifgpa
  artifact: /^Vega.*\.nupkg$/
